server:
  port: 8081

spring:
  application:
    name: auth-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/eventhub_auth}

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250655368566D5971
  expiration: 86400000

api:
  key: ${AUTH_SERVICE_KEY:auth-service-secret-key-12345}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
