server:
  port: 8084

spring:
  application:
    name: payment-notification-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27020/eventhub_payment}

api:
  key: ${PAYMENT_NOTIFICATION_KEY:payment-service-secret-key-12345}

services:
  booking:
    url: ${BOOKING_SERVICE_URL:http://localhost:8083}
    key: ${BOOKING_SERVICE_KEY:booking-service-secret-key-12345}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
