server:
  port: 8083

spring:
  application:
    name: booking-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27019/eventhub_booking}

api:
  key: ${BOOKING_SERVICE_KEY:booking-service-secret-key-12345}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
