server:
  port: 8082

spring:
  application:
    name: event-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27018/eventhub_event}

api:
  key: ${EVENT_SERVICE_KEY:event-service-secret-key-12345}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

logging:
  level:
    com.eventhub.event: DEBUG
